config/routes.rb
GRC::Application.routes.draw do


  resources :rcrievals


  resources :rgroups


  resources :revents


  resources :rcauses


  resources :rinits


  resources :recommendations


  resources :homes


  resources :arecos


  resources :aactios


  resources :areports


  resources :ainits


  resources :page


  resources :users


  resources :sessions 
  

  resources :question

 
 
  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

match "question/new" => "question#new"








    root :to => 'sessions#new'


end

app/models/aactio.rb
class Aactio < ActiveRecord::Base
  attr_accessible :ClosedDate, :Descriptions, :DueDate, :ExternalReference, :Recommendations, :Refernce, :Title, :status
 belongs_to :ainit
 belongs_to :areport
 belongs_to :areco  
end

app/models/ainit.rb
class Ainit < ActiveRecord::Base
  attr_accessible :Compliance, :Context, :Deliverables, :Objective, :Origin, :Refernce, :Scope, :Standard, :Status, :Topic
 has_one :areport
 has_many :areco
 has_many :aactio


end

app/models/approval.rb
class Approval < ActiveRecord::Base
  attr_accessible :name, :responsible, :status, :string, :version
end

app/models/arec.rb
class Arec < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/areco.rb
class Areco < ActiveRecord::Base
  attr_accessible :Atitle, :Ctitle, :Dtitle, :Title, :apriority, :aseverity, :atartget,  :auditee, :auditor,  :blocked, :closed,:compliance,:confidential,:ctarget,:ddtitle,:dependent,:description,:dreference,:dtype,:duplicate,:kind, :level,:org, :primary,:priority,:refer,:reference,:secondary,:severity,:status,:target,:compliancetype,:verification,:verified
  belongs_to :ainit
  belongs_to :areport
  has_many :aactio 

  # @areco = Areco.create(:ainit_id => @ainit)

  # @areco = Areco.where(:ainit_id => @ainit)
  # @areco.each do |areco|
  # 	areco.destory
  # end
  # @ainit.destory

end

app/models/areport.rb
class Areport < ActiveRecord::Base
  attr_accessible :Actions, :Duedate, :Recommendations, :Source, :Status, :Summary, :Title
  belongs_to :ainit
  # has_many :areco
  # has_many :aactio

	# @Areport = Areport.create(:areport_date => Time.now, :ainit_id => @ainit.id)  

	# @areport = Areport.where(:ainit_id => @ainit.id)	
	# @areport.each do |areport|
	# 	report.destory
	# end 
	# @ainit.destory
end

app/models/pinit.rb
class Pinit < ActiveRecord::Base
  attr_accessible :area, :author, :class, :description, :keyword, :name, :publishdate, :revision, :type, :version
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  attr_accessible :area, :author, :class, :description, :keyword, :name, :publishdate, :revision, :type, :version
end

app/models/publish.rb
class Publish < ActiveRecord::Base
  attr_accessible :name, :responsible, :status
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :new
end

app/models/rcause.rb
class Rcause < ActiveRecord::Base
  attr_accessible :description, :horizon_end_date, :horizon_start_date, :likelihood, :occurence_count, :period, :probability, :reference, :title
end

app/models/rcrieval.rb
class Rcrieval < ActiveRecord::Base
  attr_accessible :category, :description, :exp_ans_type, :exp_for_eval, :reference
end

app/models/revent.rb
class Revent < ActiveRecord::Base
  attr_accessible :category, :description, :likelihood, :period, :probability, :reference, :title
end

app/models/rgroup.rb
class Rgroup < ActiveRecord::Base
  attr_accessible :description, :group_name
end

app/models/rinit.rb
class Rinit < ActiveRecord::Base
  attr_accessible :category, :description, :expiration_date, :forced_review, :likelihood, :reference, :review_period, :standard, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create 
  validates_presence_of :email 
  validates_uniqueness_of :email 
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_length_of :password, :minimum => 8, :allow_blank => true
  
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/revents_controller.rb
class ReventsController < ApplicationController
  # GET /revents
  # GET /revents.json
  def index
    @revents = Revent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @revents }
    end
  end

  # GET /revents/1
  # GET /revents/1.json
  def show
    @revent = Revent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @revent }
    end
  end

  # GET /revents/new
  # GET /revents/new.json
  def new
    @revent = Revent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @revent }
    end
  end

  # GET /revents/1/edit
  def edit
    @revent = Revent.find(params[:id])
  end

  # POST /revents
  # POST /revents.json
  def create
    @revent = Revent.new(params[:revent])

    respond_to do |format|
      if @revent.save
        format.html { redirect_to @revent, notice: 'Revent was successfully created.' }
        format.json { render json: @revent, status: :created, location: @revent }
      else
        format.html { render action: "new" }
        format.json { render json: @revent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /revents/1
  # PUT /revents/1.json
  def update
    @revent = Revent.find(params[:id])

    respond_to do |format|
      if @revent.update_attributes(params[:revent])
        format.html { redirect_to @revent, notice: 'Revent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @revent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revents/1
  # DELETE /revents/1.json
  def destroy
    @revent = Revent.find(params[:id])
    @revent.destroy

    respond_to do |format|
      format.html { redirect_to revents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ainits_helper.rb
module AinitsHelper
end

app/helpers/arecos_helper.rb
module ArecosHelper
end

app/helpers/arecs_helper.rb
module ArecsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/revents_helper.rb
module ReventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/revents/_form.html.erb
<%= form_for(@revent) do |f| %>
  <% if @revent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@revent.errors.count, "error") %> prohibited this revent from being saved:</h2>

      <ul>
      <% @revent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :reference %><br />
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :period %><br />
    <%= f.number_field :period %>
  </div>
  <div class="field">
    <%= f.label :likelihood %><br />
    <%= f.text_field :likelihood %>
  </div>
  <div class="field">
    <%= f.label :probability %><br />
    <%= f.text_field :probability %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/revents/edit.html.erb
<div class="container">

	<div class="row">
		<div class="span9 offset1 well">            
			<legend>Edit Event</legend>



			<%= render 'form' %>

			<%= link_to 'Show', @revent %> |
			<%= link_to 'Back', revents_path %>


		</div>

		<div class="row">
			<div class="span2 offset well">        
				<legend>Quick Links</legend>
				<p>
					<%= link_to 'Risks', rinits_path %> <br />          
					<%= link_to 'Events', revents_path %> <br />          
				</p>        
			</div>

			<div class="span2 offset well">        
				<legend>Goto</legend>
				<p>
					<%= button_to "Risks Management", new_rinit_path, :method => :get, :class => "btn btn-success" %>          
				</p>        
			</div>
		</div>
	</div>

</div>

app/views/revents/index.html.erb
<%= render :partial => 'layouts/header' %>
<br />
<br />
<!-- <div class="container"> -->

    <div class="row">
        <div class="span11 offset1 well">
            <h3>Risks Modelisation</h3>
            <legend>Events</legend>

            <table class="table">
              <tr>
                <th>Title</th>
                <th>Reference</th>
                <th>Category</th>
                <th>Period</th>
                <th>Likelihood</th>     
                <th></th>
                <th></th>
                <th></th>
            </tr>

            <% @revents.each do |revent| %>
            <tr>
                <td><%= revent.title %></td>
                <td><%= revent.reference %></td>
                <td><%= revent.category %></td>
                <td><%= revent.period %></td>
                <td><%= revent.likelihood %></td>
                <td><%= link_to '', revent, :class => "icon-list-alt icon-white" %></td>
                <td><%= link_to '', edit_revent_path(revent), :class => "icon-pencil icon-white" %></td>
                <td><%= link_to '', revent, method: :delete, data: { confirm: 'Are you sure?' }, :class => "icon-trash icon-white" %></td>
            </tr>
            <% end %>
        </table>

        <br />
        
        <%= button_to "New", new_revent_path, :method => :get, :class => "btn btn-primary" %>

    </div>

    <div class="row">      
      <div class="span2 offset well">        
        <legend>Quick Links</legend>
        <p>
            <%= link_to 'Risks', rinits_path %> <br />          
            <%= link_to 'Causes', rcauses_path %> <br />
        </p>        
    </div>
    <div class="span2 offset well">        
        <legend>Goto</legend>
        <p>
          <%= button_to "Risks Management", rgroups_path, :method => :get, :class => "btn btn-success" %>          
        </p>        
      </div>
    </div>
</div>
<!-- </div> -->

app/views/revents/new.html.erb
<h1>New revent</h1>

<%= render 'form' %>

<%= link_to 'Back', revents_path %>

app/views/revents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @revent.title %>
</p>

<p>
  <b>Reference:</b>
  <%= @revent.reference %>
</p>

<p>
  <b>Description:</b>
  <%= @revent.description %>
</p>

<p>
  <b>Category:</b>
  <%= @revent.category %>
</p>

<p>
  <b>Period:</b>
  <%= @revent.period %>
</p>

<p>
  <b>Likelihood:</b>
  <%= @revent.likelihood %>
</p>

<p>
  <b>Probability:</b>
  <%= @revent.probability %>
</p>


<%= link_to 'Edit', edit_revent_path(@revent) %> |
<%= link_to 'Back', revents_path %>