config/routes.rb
GRC::Application.routes.draw do


  resources :rcrievals


  resources :rgroups


  resources :revents


  resources :rcauses


  resources :rinits


  resources :recommendations


  resources :homes


  resources :arecos


  resources :aactios


  resources :areports


  resources :ainits


  resources :page


  resources :users


  resources :sessions 
  

  resources :question

 
 
  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

match "question/new" => "question#new"








    root :to => 'sessions#new'


end

app/models/aactio.rb
class Aactio < ActiveRecord::Base
  attr_accessible :ClosedDate, :Descriptions, :DueDate, :ExternalReference, :Recommendations, :Refernce, :Title, :status
 belongs_to :ainit
 belongs_to :areport
 belongs_to :areco  
end

app/models/ainit.rb
class Ainit < ActiveRecord::Base
  attr_accessible :Compliance, :Context, :Deliverables, :Objective, :Origin, :Refernce, :Scope, :Standard, :Status, :Topic
 has_one :areport
 has_many :areco
 has_many :aactio


end

app/models/approval.rb
class Approval < ActiveRecord::Base
  attr_accessible :name, :responsible, :status, :string, :version
end

app/models/arec.rb
class Arec < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/areco.rb
class Areco < ActiveRecord::Base
  attr_accessible :Atitle, :Ctitle, :Dtitle, :Title, :apriority, :aseverity, :atartget,  :auditee, :auditor,  :blocked, :closed,:compliance,:confidential,:ctarget,:ddtitle,:dependent,:description,:dreference,:dtype,:duplicate,:kind, :level,:org, :primary,:priority,:refer,:reference,:secondary,:severity,:status,:target,:compliancetype,:verification,:verified
  belongs_to :ainit
  belongs_to :areport
  has_many :aactio 

  # @areco = Areco.create(:ainit_id => @ainit)

  # @areco = Areco.where(:ainit_id => @ainit)
  # @areco.each do |areco|
  # 	areco.destory
  # end
  # @ainit.destory

end

app/models/areport.rb
class Areport < ActiveRecord::Base
  attr_accessible :Actions, :Duedate, :Recommendations, :Source, :Status, :Summary, :Title
  belongs_to :ainit
  # has_many :areco
  # has_many :aactio

	# @Areport = Areport.create(:areport_date => Time.now, :ainit_id => @ainit.id)  

	# @areport = Areport.where(:ainit_id => @ainit.id)	
	# @areport.each do |areport|
	# 	report.destory
	# end 
	# @ainit.destory
end

app/models/pinit.rb
class Pinit < ActiveRecord::Base
  attr_accessible :area, :author, :class, :description, :keyword, :name, :publishdate, :revision, :type, :version
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  attr_accessible :area, :author, :class, :description, :keyword, :name, :publishdate, :revision, :type, :version
end

app/models/publish.rb
class Publish < ActiveRecord::Base
  attr_accessible :name, :responsible, :status
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :new
end

app/models/rcause.rb
class Rcause < ActiveRecord::Base
  attr_accessible :description, :horizon_end_date, :horizon_start_date, :likelihood, :occurence_count, :period, :probability, :reference, :title
end

app/models/rcrieval.rb
class Rcrieval < ActiveRecord::Base
  attr_accessible :category, :description, :exp_ans_type, :exp_for_eval, :reference
end

app/models/revent.rb
class Revent < ActiveRecord::Base
  attr_accessible :category, :description, :likelihood, :period, :probability, :reference, :title
end

app/models/rgroup.rb
class Rgroup < ActiveRecord::Base
  attr_accessible :description, :group_name
end

app/models/rinit.rb
class Rinit < ActiveRecord::Base
  attr_accessible :category, :description, :expiration_date, :forced_review, :likelihood, :reference, :review_period, :standard, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create 
  validates_presence_of :email 
  validates_uniqueness_of :email 
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_length_of :password, :minimum => 8, :allow_blank => true
  
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/rgroups_controller.rb
class RgroupsController < ApplicationController
  # GET /rgroups
  # GET /rgroups.json
  def index
    @rgroups = Rgroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rgroups }
    end
  end

  # GET /rgroups/1
  # GET /rgroups/1.json
  def show
    @rgroup = Rgroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rgroup }
    end
  end

  # GET /rgroups/new
  # GET /rgroups/new.json
  def new
    @rgroup = Rgroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rgroup }
    end
  end

  # GET /rgroups/1/edit
  def edit
    @rgroup = Rgroup.find(params[:id])
  end

  # POST /rgroups
  # POST /rgroups.json
  def create
    @rgroup = Rgroup.new(params[:rgroup])

    respond_to do |format|
      if @rgroup.save
        format.html { redirect_to @rgroup, notice: 'Rgroup was successfully created.' }
        format.json { render json: @rgroup, status: :created, location: @rgroup }
      else
        format.html { render action: "new" }
        format.json { render json: @rgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rgroups/1
  # PUT /rgroups/1.json
  def update
    @rgroup = Rgroup.find(params[:id])

    respond_to do |format|
      if @rgroup.update_attributes(params[:rgroup])
        format.html { redirect_to @rgroup, notice: 'Rgroup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rgroups/1
  # DELETE /rgroups/1.json
  def destroy
    @rgroup = Rgroup.find(params[:id])
    @rgroup.destroy

    respond_to do |format|
      format.html { redirect_to rgroups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ainits_helper.rb
module AinitsHelper
end

app/helpers/arecos_helper.rb
module ArecosHelper
end

app/helpers/arecs_helper.rb
module ArecsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/rgroups_helper.rb
module RgroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rgroups/_form.html.erb
<%= form_for(@rgroup) do |f| %>
  <% if @rgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rgroup.errors.count, "error") %> prohibited this rgroup from being saved:</h2>

      <ul>
      <% @rgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_name %><br />
    <%= f.text_field :group_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rgroups/edit.html.erb
<h1>Editing rgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @rgroup %> |
<%= link_to 'Back', rgroups_path %>

app/views/rgroups/index.html.erb
<%= render :partial => 'layouts/header' %>
<br />
<br />
<!-- <div class="container"> -->

  <div class="row">
    <div class="span11 offset1 well">
      <h3>Risk Management</h3>
      <legend>Groups</legend>

      <table class="table">
        <tr>
          <th>Group Name</th>
          <th>Description</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @rgroups.each do |rgroup| %>
        <tr>
          <td><%= rgroup.group_name %></td>
          <td><%= rgroup.description %></td>
          <td><%= link_to '', rgroup, :class =>"icon-list-alt icon-white" %></td>
          <td><%= link_to '', edit_rgroup_path(rgroup), :class => "icon-pencil icon-white" %></td>
          <td><%= link_to '', rgroup, method: :delete, data: { confirm: 'Are you sure?' }, :class => "icon-trash icon-white" %></td>
        </tr>
        <% end %>
      </table>

      <br />

      <%= link_to 'New', new_rgroup_path %>

    </div>



    <div class="row">
      <div class="span2 offset well">        
        <legend>Quick Links</legend>
        <p>
          <%= link_to 'Criteria', rcrievals_path %> <br />          
        </p>        
      </div>

      <div class="span2 offset well">        
        <legend>Goto</legend>
        <p>
          <%= button_to "Risks Modelisation", rinits_path, :method => :get, :class => "btn btn-success" %>          
        </p>        
      </div>
    </div>
  </div>

<!-- </div> -->

app/views/rgroups/new.html.erb
<h1>New rgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', rgroups_path %>

app/views/rgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group name:</b>
  <%= @rgroup.group_name %>
</p>

<p>
  <b>Description:</b>
  <%= @rgroup.description %>
</p>


<%= link_to 'Edit', edit_rgroup_path(@rgroup) %> |
<%= link_to 'Back', rgroups_path %>